### ISSUE TITLE
Toggle Pause not working by shortcut

### ISSUE THREAD

**Issue by Vasllo** [dvlden/ultrawideo#20] opened 2019-09-07 14:08 UTC
The shortcut only pauses, doesn't unpause, tried to reinstall and several shortcut combinations. This is quite crucial to me, otherwise it becomes a hassle to have to open the menu and click to unpause it every time. Hope this gets fixed soon, thanks for your good work.

**Comment by dvlden** [comment] 2019-09-07 15:53
Duplicate of #17 

This is the intended behavior. Don't pause it, if all you're trying to do is go back to `normal` mode.
The `normal` mode, basically does nothing. It won't affect videos that are playing, so that's the mode you should be using if you don't want the extension to modify the aspect ratio.

Pause - pauses all of the event listeners, so manual unpause by click is actually a requirement.

**Closed by dvlden** 2019-09-07 15:53 UTC

**Comment by Vasllo** [comment] 2019-09-08 13:18
But the name is "toggle", why shouldn't it toggle between paused and unpaused? It's much easier than navigate through the modes, which isn't that great since I can't keep CTRL + ALT pressed while I change just pressing C a few times (like I could in my Chrome extension, it was faster that way). Stretch isn't usable for me, so scrolling through it is a waste of time tbh (I know it's not a huge deal, but still, quality of life improvements).

Also, is it possible to add 18:9 content crop to 21:9? Because the 18:9 content end up with cut parts on top and bottom. And I always wandered, is it even possible to make it automatically adjust to the screen based on the presence of black bars on top and bottom, independently from the aspect ratio?

**Comment by dvlden** [comment] 2019-09-08 13:56
Yes, and toggle functionality is working. 
Toggle it entirely via click (on/off) or (on) via keyboard and (off) via click.

If I were to make toggle work with keyboard shortcuts, then we're not really pausing the extension, but DOM manipulation only. Not sure how I feel about this...

Yes, it can be annoying accidentally disabling the extension via a keyboard shortcut, but if it's intentionally disabled, it's probably for a longer period and disabling the pause via click seems fine.

Can you clarify to me what do you mean, you can't keep `ctrl + alt` pressed while pressing `C`? You should be able to toggle between modes like so: `ctrl + alt` + `c`... (multiple times pressing c)

Regarding your last question, it is not possible. The extension does not use any expensive JS calculations for the aspect ratio, but rather uses CSS so that the browser itself can handle this.

**Comment by Vasllo** [comment] 2019-09-08 20:32
Thanks for the clarifications.

And the issue I'm having is that I can't keep CTRL and ALT pressed while I press C multiple times to navigate the modes, every time I change mode, I have to release CTRL and ALT then press them again or it won't change modes.

**Comment by dvlden** [comment] 2019-09-08 21:42
Oh wow, that shouldn't be the case. Let me check real quick what does the test says.
