### ISSUE TITLE
Normal mode acting strangely in Firefox

### ISSUE THREAD

**Issue by JonathanTaylor9** [dvlden/ultrawideo#74] opened 2022-04-21 18:38 UTC
For the last couple of days, I've noticed a strange symptom when maximising a video in Normal mode, using Firefox on PC - this was affecting a Football Stream yesterday, and today I've noticed it also it's affecting Amazon Prime Video.  I run 3440 * 1440 resolution.  Rather than just maximise the video without cropping it or altering it as it used to, it's making the video small and appearing in the centre of the screen.

Here's an example:

![image](https://user-images.githubusercontent.com/65346162/164530370-f164b7fc-d4e6-4bf3-9045-f3299dd19398.png)

**Comment by JonathanTaylor9** [comment] 2022-04-21 18:47
Running version 2.5.0 by the way

**Comment by dvlden** [comment] 2022-04-21 19:33
Hey! Thanks for opening up an issue.
This has been fixed in 2.5.1 now. Just wait for the update on the Firefox store. You should get it automatically...

Duplicate of #72

**Closed** 2022-04-21 19:33 UTC

**Comment by JonathanTaylor9** [comment] 2022-04-22 06:54
Excellent, thanks.  I just updated to 2.5.1 and now Prime's working again, so looks good.
